// Comprehensive RBAC Permission System
// Permissions follow format: resource.action (e.g., users.read, exams.create)

export const PERMISSIONS = {
  // User management
  USERS_CREATE: 'users.create',
  USERS_READ: 'users.read',
  USERS_UPDATE: 'users.update',
  USERS_DELETE: 'users.delete',
  USERS_MANAGE: 'users.manage',
  USERS_SUSPEND: 'users.suspend',
  USERS_ROLE_UPDATE: 'users.role.update',

  // Subject management
  SUBJECTS_CREATE: 'subjects.create',
  SUBJECTS_READ: 'subjects.read',
  SUBJECTS_UPDATE: 'subjects.update',
  SUBJECTS_DELETE: 'subjects.delete',
  SUBJECTS_MANAGE: 'subjects.manage',

  // Exam management
  EXAMS_CREATE: 'exams.create',
  EXAMS_READ: 'exams.read',
  EXAMS_UPDATE: 'exams.update',
  EXAMS_DELETE: 'exams.delete',
  EXAMS_MANAGE: 'exams.manage',
  EXAMS_TAKE: 'exams.take',

  // Assignment management
  ASSIGNMENTS_CREATE: 'assignments.create',
  ASSIGNMENTS_READ: 'assignments.read',
  ASSIGNMENTS_UPDATE: 'assignments.update',
  ASSIGNMENTS_DELETE: 'assignments.delete',
  ASSIGNMENTS_MANAGE: 'assignments.manage',

  // Notes management
  NOTES_CREATE: 'notes.create',
  NOTES_READ: 'notes.read',
  NOTES_UPDATE: 'notes.update',
  NOTES_DELETE: 'notes.delete',
  NOTES_MANAGE: 'notes.manage',

  // Storage management
  STORAGE_UPLOAD: 'storage.upload',
  STORAGE_READ: 'storage.read',
  STORAGE_DELETE: 'storage.delete',
  STORAGE_MANAGE: 'storage.manage',

  // Results management
  RESULTS_CREATE: 'results.create',
  RESULTS_READ: 'results.read',
  RESULTS_UPDATE: 'results.update',
  RESULTS_DELETE: 'results.delete',
  RESULTS_MANAGE: 'results.manage',

  // Notifications
  NOTIFICATIONS_CREATE: 'notifications.create',
  NOTIFICATIONS_READ: 'notifications.read',
  NOTIFICATIONS_UPDATE: 'notifications.update',
  NOTIFICATIONS_DELETE: 'notifications.delete',
  NOTIFICATIONS_MANAGE: 'notifications.manage',

  // Lessons
  LESSONS_CREATE: 'lessons.create',
  LESSONS_READ: 'lessons.read',
  LESSONS_UPDATE: 'lessons.update',
  LESSONS_DELETE: 'lessons.delete',
  LESSONS_MANAGE: 'lessons.manage',

  // Submissions
  SUBMISSIONS_CREATE: 'submissions.create',
  SUBMISSIONS_READ: 'submissions.read',
  SUBMISSIONS_UPDATE: 'submissions.update',
  SUBMISSIONS_GRADE: 'submissions.grade',
  SUBMISSIONS_DELETE: 'submissions.delete',
  SUBMISSIONS_MANAGE: 'submissions.manage',

  // Schemes of work
  SCHEMES_CREATE: 'schemes.create',
  SCHEMES_READ: 'schemes.read',
  SCHEMES_UPDATE: 'schemes.update',
  SCHEMES_DELETE: 'schemes.delete',
  SCHEMES_MANAGE: 'schemes.manage',

  // Lesson plans
  LESSON_PLANS_CREATE: 'lessonPlans.create',
  LESSON_PLANS_READ: 'lessonPlans.read',
  LESSON_PLANS_UPDATE: 'lessonPlans.update',
  LESSON_PLANS_DELETE: 'lessonPlans.delete',
  LESSON_PLANS_MANAGE: 'lessonPlans.manage',

  // Midterm results
  MIDTERM_RESULTS_CREATE: 'midtermResults.create',
  MIDTERM_RESULTS_READ: 'midtermResults.read',
  MIDTERM_RESULTS_UPDATE: 'midtermResults.update',
  MIDTERM_RESULTS_DELETE: 'midtermResults.delete',
  MIDTERM_RESULTS_MANAGE: 'midtermResults.manage',

  // Attendance (period-level for subject teachers, full-day for class teachers)
  ATTENDANCE_CREATE: 'attendance.create',
  ATTENDANCE_READ: 'attendance.read',
  ATTENDANCE_UPDATE: 'attendance.update',
  ATTENDANCE_DELETE: 'attendance.delete',
  ATTENDANCE_MANAGE: 'attendance.manage',

  // Report cards (compiled by class teachers, approved by principal)
  REPORT_CARDS_CREATE: 'reportCards.create',
  REPORT_CARDS_READ: 'reportCards.read',
  REPORT_CARDS_UPDATE: 'reportCards.update',
  REPORT_CARDS_SUBMIT: 'reportCards.submit',
  REPORT_CARDS_APPROVE: 'reportCards.approve',
  REPORT_CARDS_DELETE: 'reportCards.delete',
  REPORT_CARDS_MANAGE: 'reportCards.manage',

  // Discipline (logged by teachers, escalated to & resolved by principal)
  DISCIPLINE_CREATE: 'discipline.create',
  DISCIPLINE_READ: 'discipline.read',
  DISCIPLINE_UPDATE: 'discipline.update',
  DISCIPLINE_ESCALATE: 'discipline.escalate',
  DISCIPLINE_RESOLVE: 'discipline.resolve',
  DISCIPLINE_DELETE: 'discipline.delete',
  DISCIPLINE_MANAGE: 'discipline.manage',

  // Staff requests (leave/resource asks submitted by staff, approved by principal)
  STAFF_REQUESTS_CREATE: 'staffRequests.create',
  STAFF_REQUESTS_READ: 'staffRequests.read',
  STAFF_REQUESTS_UPDATE: 'staffRequests.update',
  STAFF_REQUESTS_APPROVE: 'staffRequests.approve',
  STAFF_REQUESTS_DELETE: 'staffRequests.delete',
  STAFF_REQUESTS_MANAGE: 'staffRequests.manage',

  // Reports
  REPORTS_CREATE: 'reports.create',
  REPORTS_READ: 'reports.read',
  REPORTS_UPDATE: 'reports.update',
  REPORTS_RESOLVE: 'reports.resolve',
  REPORTS_DELETE: 'reports.delete',
  REPORTS_MANAGE: 'reports.manage',

  // Admissions
  ADMISSIONS_CREATE: 'admissions.create',
  ADMISSIONS_READ: 'admissions.read',
  ADMISSIONS_UPDATE: 'admissions.update',
  ADMISSIONS_APPROVE: 'admissions.approve',
  ADMISSIONS_REJECT: 'admissions.reject',
  ADMISSIONS_DELETE: 'admissions.delete',
  ADMISSIONS_MANAGE: 'admissions.manage',

  // Class management
  CLASSES_CREATE: 'classes.create',
  CLASSES_READ: 'classes.read',
  CLASSES_DELETE: 'classes.delete',
  CLASSES_MANAGE: 'classes.manage',

  // Audit
  AUDIT_READ: 'audit.read',

  // System (technician)
  SYSTEM_READ: 'system.read',
  SYSTEM_MANAGE: 'system.manage',

  // Devices
  DEVICES_READ: 'devices.read',
  DEVICES_MANAGE: 'devices.manage',

  // Alerts
  ALERTS_READ: 'alerts.read',
  ALERTS_MANAGE: 'alerts.manage',

  // RBAC Policies
  RBAC_READ: 'rbac.read',
  RBAC_MANAGE: 'rbac.manage',

  // Health
  HEALTH_READ: 'health.read',

  // Billing/Accounting
  BILLING_READ: 'billing.read',
  BILLING_MANAGE: 'billing.manage',

  // Expenses (recorded by accountant, signed off by principal above threshold)
  EXPENSES_CREATE: 'expenses.create',
  EXPENSES_READ: 'expenses.read',
  EXPENSES_UPDATE: 'expenses.update',
  EXPENSES_APPROVE: 'expenses.approve',
  EXPENSES_DELETE: 'expenses.delete',
  EXPENSES_MANAGE: 'expenses.manage',

  // Institutions
  INSTITUTIONS_READ: 'institutions.read',
  INSTITUTIONS_MANAGE: 'institutions.manage',

  // Platform settings
  PLATFORM_SETTINGS_READ: 'platformSettings.read',
  PLATFORM_SETTINGS_MANAGE: 'platformSettings.manage',

  // Backups
  BACKUPS_READ: 'backups.read',
  BACKUPS_MANAGE: 'backups.manage',

  // Audit
  AUDIT_CLEAR: 'audit.clear',

  // Children (parent)
  CHILDREN_READ: 'children.read',
  CHILDREN_GRADES_READ: 'children.grades.read',
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];

// Role-based permission mappings
export const ROLE_PERMISSIONS: Record<string, string[]> = {
   superadmin: ['*'], // Superadmin has ALL permissions
   admin: [
     PERMISSIONS.USERS_CREATE, PERMISSIONS.USERS_READ, PERMISSIONS.USERS_UPDATE, PERMISSIONS.USERS_DELETE, PERMISSIONS.USERS_MANAGE, PERMISSIONS.USERS_SUSPEND, PERMISSIONS.USERS_ROLE_UPDATE,
     PERMISSIONS.SUBJECTS_CREATE, PERMISSIONS.SUBJECTS_READ, PERMISSIONS.SUBJECTS_UPDATE, PERMISSIONS.SUBJECTS_DELETE, PERMISSIONS.SUBJECTS_MANAGE,
     PERMISSIONS.EXAMS_MANAGE, PERMISSIONS.EXAMS_READ,
     PERMISSIONS.ASSIGNMENTS_MANAGE, PERMISSIONS.ASSIGNMENTS_READ,
      PERMISSIONS.NOTES_CREATE, PERMISSIONS.NOTES_READ, PERMISSIONS.NOTES_UPDATE, PERMISSIONS.NOTES_DELETE, PERMISSIONS.NOTES_MANAGE,
     PERMISSIONS.STORAGE_MANAGE, PERMISSIONS.STORAGE_READ,
     PERMISSIONS.RESULTS_MANAGE, PERMISSIONS.RESULTS_READ,
     PERMISSIONS.NOTIFICATIONS_CREATE, PERMISSIONS.NOTIFICATIONS_READ, PERMISSIONS.NOTIFICATIONS_UPDATE, PERMISSIONS.NOTIFICATIONS_DELETE, PERMISSIONS.NOTIFICATIONS_MANAGE,
     PERMISSIONS.LESSONS_MANAGE, PERMISSIONS.LESSONS_READ,
     PERMISSIONS.SUBMISSIONS_MANAGE, PERMISSIONS.SUBMISSIONS_READ, PERMISSIONS.SUBMISSIONS_GRADE,
     PERMISSIONS.SCHEMES_MANAGE, PERMISSIONS.SCHEMES_READ,
     PERMISSIONS.LESSON_PLANS_MANAGE, PERMISSIONS.LESSON_PLANS_READ,
     PERMISSIONS.MIDTERM_RESULTS_MANAGE, PERMISSIONS.MIDTERM_RESULTS_READ,
     PERMISSIONS.ATTENDANCE_MANAGE, PERMISSIONS.ATTENDANCE_READ,
     PERMISSIONS.REPORT_CARDS_MANAGE, PERMISSIONS.REPORT_CARDS_READ, PERMISSIONS.REPORT_CARDS_APPROVE,
     PERMISSIONS.DISCIPLINE_MANAGE, PERMISSIONS.DISCIPLINE_READ, PERMISSIONS.DISCIPLINE_ESCALATE, PERMISSIONS.DISCIPLINE_RESOLVE,
     PERMISSIONS.STAFF_REQUESTS_MANAGE, PERMISSIONS.STAFF_REQUESTS_READ, PERMISSIONS.STAFF_REQUESTS_APPROVE,
     PERMISSIONS.EXPENSES_MANAGE, PERMISSIONS.EXPENSES_READ, PERMISSIONS.EXPENSES_APPROVE,
     PERMISSIONS.REPORTS_MANAGE, PERMISSIONS.REPORTS_READ, PERMISSIONS.REPORTS_RESOLVE,
     PERMISSIONS.ADMISSIONS_MANAGE, PERMISSIONS.ADMISSIONS_READ, PERMISSIONS.ADMISSIONS_APPROVE, PERMISSIONS.ADMISSIONS_REJECT,
      PERMISSIONS.CLASSES_CREATE, PERMISSIONS.CLASSES_READ, PERMISSIONS.CLASSES_DELETE, PERMISSIONS.CLASSES_MANAGE,
      PERMISSIONS.AUDIT_READ,
       PERMISSIONS.AUDIT_CLEAR,
       PERMISSIONS.HEALTH_READ,
       PERMISSIONS.INSTITUTIONS_READ,
      PERMISSIONS.INSTITUTIONS_MANAGE,
      PERMISSIONS.PLATFORM_SETTINGS_READ,
      PERMISSIONS.PLATFORM_SETTINGS_MANAGE,
      PERMISSIONS.BACKUPS_READ,
      PERMISSIONS.BACKUPS_MANAGE,
   ],
teacher: [
    PERMISSIONS.USERS_READ,
    PERMISSIONS.EXAMS_CREATE, PERMISSIONS.EXAMS_READ, PERMISSIONS.EXAMS_UPDATE, PERMISSIONS.EXAMS_DELETE,
    PERMISSIONS.ASSIGNMENTS_CREATE, PERMISSIONS.ASSIGNMENTS_READ, PERMISSIONS.ASSIGNMENTS_UPDATE, PERMISSIONS.ASSIGNMENTS_DELETE,
    PERMISSIONS.NOTES_CREATE, PERMISSIONS.NOTES_READ, PERMISSIONS.NOTES_UPDATE, PERMISSIONS.NOTES_DELETE,
    PERMISSIONS.RESULTS_CREATE, PERMISSIONS.RESULTS_READ, PERMISSIONS.RESULTS_UPDATE,
    PERMISSIONS.NOTIFICATIONS_READ, PERMISSIONS.NOTIFICATIONS_UPDATE, PERMISSIONS.NOTIFICATIONS_DELETE,
    PERMISSIONS.LESSONS_CREATE, PERMISSIONS.LESSONS_READ, PERMISSIONS.LESSONS_UPDATE, PERMISSIONS.LESSONS_DELETE,
    PERMISSIONS.SUBMISSIONS_READ, PERMISSIONS.SUBMISSIONS_GRADE,
    PERMISSIONS.SCHEMES_CREATE, PERMISSIONS.SCHEMES_READ, PERMISSIONS.SCHEMES_UPDATE, PERMISSIONS.SCHEMES_DELETE,
    PERMISSIONS.LESSON_PLANS_CREATE, PERMISSIONS.LESSON_PLANS_READ, PERMISSIONS.LESSON_PLANS_UPDATE, PERMISSIONS.LESSON_PLANS_DELETE,
    PERMISSIONS.MIDTERM_RESULTS_CREATE, PERMISSIONS.MIDTERM_RESULTS_READ, PERMISSIONS.MIDTERM_RESULTS_UPDATE,
    PERMISSIONS.ATTENDANCE_CREATE, PERMISSIONS.ATTENDANCE_READ, PERMISSIONS.ATTENDANCE_UPDATE, PERMISSIONS.ATTENDANCE_DELETE,
    PERMISSIONS.REPORT_CARDS_CREATE, PERMISSIONS.REPORT_CARDS_READ, PERMISSIONS.REPORT_CARDS_UPDATE, PERMISSIONS.REPORT_CARDS_SUBMIT,
    PERMISSIONS.DISCIPLINE_CREATE, PERMISSIONS.DISCIPLINE_READ, PERMISSIONS.DISCIPLINE_UPDATE, PERMISSIONS.DISCIPLINE_ESCALATE,
    PERMISSIONS.STAFF_REQUESTS_CREATE, PERMISSIONS.STAFF_REQUESTS_READ, PERMISSIONS.STAFF_REQUESTS_UPDATE,
  ],
  student: [
    PERMISSIONS.NOTES_READ,
    PERMISSIONS.ASSIGNMENTS_READ,
    PERMISSIONS.EXAMS_READ, PERMISSIONS.EXAMS_TAKE,
    PERMISSIONS.SUBMISSIONS_CREATE,
    PERMISSIONS.RESULTS_READ,
    PERMISSIONS.LESSONS_READ,
    PERMISSIONS.NOTIFICATIONS_READ, PERMISSIONS.NOTIFICATIONS_UPDATE, PERMISSIONS.NOTIFICATIONS_DELETE,
    PERMISSIONS.REPORTS_CREATE,
  ],
  accountant: [
    PERMISSIONS.BILLING_READ, PERMISSIONS.BILLING_MANAGE,
    PERMISSIONS.USERS_READ,
    PERMISSIONS.NOTIFICATIONS_READ, PERMISSIONS.NOTIFICATIONS_UPDATE, PERMISSIONS.NOTIFICATIONS_DELETE,
    PERMISSIONS.STAFF_REQUESTS_CREATE, PERMISSIONS.STAFF_REQUESTS_READ,
    PERMISSIONS.EXPENSES_CREATE, PERMISSIONS.EXPENSES_READ, PERMISSIONS.EXPENSES_UPDATE,
  ],
  technician: [
    PERMISSIONS.SYSTEM_READ, PERMISSIONS.SYSTEM_MANAGE,
    PERMISSIONS.DEVICES_READ, PERMISSIONS.DEVICES_MANAGE,
    PERMISSIONS.ALERTS_READ, PERMISSIONS.ALERTS_MANAGE,
    PERMISSIONS.RBAC_READ,
    PERMISSIONS.HEALTH_READ,
    PERMISSIONS.NOTIFICATIONS_READ, PERMISSIONS.NOTIFICATIONS_UPDATE, PERMISSIONS.NOTIFICATIONS_DELETE,
    PERMISSIONS.STAFF_REQUESTS_CREATE, PERMISSIONS.STAFF_REQUESTS_READ,
  ],
  principal: [
    PERMISSIONS.USERS_READ, PERMISSIONS.USERS_UPDATE, PERMISSIONS.USERS_SUSPEND,
    PERMISSIONS.SUBJECTS_READ,
    PERMISSIONS.CLASSES_READ,
    PERMISSIONS.BILLING_READ,
    PERMISSIONS.EXAMS_READ, PERMISSIONS.EXAMS_MANAGE,
    PERMISSIONS.ASSIGNMENTS_READ, PERMISSIONS.ASSIGNMENTS_MANAGE,
    PERMISSIONS.NOTES_READ,
    PERMISSIONS.RESULTS_READ, PERMISSIONS.RESULTS_MANAGE,
    PERMISSIONS.NOTIFICATIONS_CREATE, PERMISSIONS.NOTIFICATIONS_READ, PERMISSIONS.NOTIFICATIONS_UPDATE, PERMISSIONS.NOTIFICATIONS_DELETE, PERMISSIONS.NOTIFICATIONS_MANAGE,
    PERMISSIONS.LESSONS_READ,
    PERMISSIONS.SUBMISSIONS_READ,
    PERMISSIONS.REPORTS_READ, PERMISSIONS.REPORTS_RESOLVE,
    PERMISSIONS.ADMISSIONS_READ, PERMISSIONS.ADMISSIONS_APPROVE, PERMISSIONS.ADMISSIONS_REJECT,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.HEALTH_READ,
    PERMISSIONS.SCHEMES_READ, PERMISSIONS.SCHEMES_UPDATE,
    PERMISSIONS.LESSON_PLANS_READ, PERMISSIONS.LESSON_PLANS_UPDATE,
    PERMISSIONS.MIDTERM_RESULTS_READ, PERMISSIONS.MIDTERM_RESULTS_MANAGE,
    PERMISSIONS.ATTENDANCE_READ, PERMISSIONS.ATTENDANCE_MANAGE,
    PERMISSIONS.REPORT_CARDS_READ, PERMISSIONS.REPORT_CARDS_APPROVE,
    PERMISSIONS.DISCIPLINE_READ, PERMISSIONS.DISCIPLINE_RESOLVE, PERMISSIONS.DISCIPLINE_DELETE,
    PERMISSIONS.STAFF_REQUESTS_READ, PERMISSIONS.STAFF_REQUESTS_APPROVE, PERMISSIONS.STAFF_REQUESTS_MANAGE,
    PERMISSIONS.EXPENSES_READ, PERMISSIONS.EXPENSES_APPROVE,
  ],
  hod: [
    PERMISSIONS.USERS_READ,
    PERMISSIONS.SUBJECTS_READ,
    PERMISSIONS.EXAMS_READ, PERMISSIONS.EXAMS_MANAGE,
    PERMISSIONS.ASSIGNMENTS_READ, PERMISSIONS.ASSIGNMENTS_MANAGE,
    PERMISSIONS.NOTES_READ,
    PERMISSIONS.RESULTS_READ, PERMISSIONS.RESULTS_MANAGE,
    PERMISSIONS.NOTIFICATIONS_CREATE, PERMISSIONS.NOTIFICATIONS_READ, PERMISSIONS.NOTIFICATIONS_UPDATE, PERMISSIONS.NOTIFICATIONS_DELETE,
    PERMISSIONS.LESSONS_READ,
    PERMISSIONS.SUBMISSIONS_READ,
    PERMISSIONS.REPORTS_READ, PERMISSIONS.REPORTS_RESOLVE,
    PERMISSIONS.ADMISSIONS_READ,
    PERMISSIONS.HEALTH_READ,
    PERMISSIONS.SCHEMES_READ, PERMISSIONS.SCHEMES_UPDATE,
    PERMISSIONS.LESSON_PLANS_READ, PERMISSIONS.LESSON_PLANS_UPDATE,
    PERMISSIONS.MIDTERM_RESULTS_READ, PERMISSIONS.MIDTERM_RESULTS_MANAGE,
    PERMISSIONS.ATTENDANCE_READ, PERMISSIONS.ATTENDANCE_MANAGE,
    PERMISSIONS.DISCIPLINE_READ, PERMISSIONS.DISCIPLINE_ESCALATE,
    PERMISSIONS.STAFF_REQUESTS_CREATE, PERMISSIONS.STAFF_REQUESTS_READ,
  ],
  parent: [
    PERMISSIONS.CHILDREN_READ, PERMISSIONS.CHILDREN_GRADES_READ,
    PERMISSIONS.NOTIFICATIONS_READ, PERMISSIONS.NOTIFICATIONS_UPDATE, PERMISSIONS.NOTIFICATIONS_DELETE,
    PERMISSIONS.RESULTS_READ, PERMISSIONS.BILLING_READ,
    PERMISSIONS.EXAMS_READ, PERMISSIONS.ASSIGNMENTS_READ, PERMISSIONS.NOTES_READ,
    PERMISSIONS.REPORT_CARDS_READ,
  ],
};

export const PERMISSION_PATTERNS = {
  users: ['create', 'read', 'update', 'delete', 'manage'],
  subjects: ['create', 'read', 'update', 'delete', 'manage'],
  exams: ['create', 'read', 'update', 'delete', 'manage', 'take'],
  assignments: ['create', 'read', 'update', 'delete', 'manage'],
  notes: ['create', 'read', 'update', 'delete', 'manage'],
  storage: ['create', 'read', 'update', 'delete', 'manage'],
  billing: ['create', 'read', 'update', 'delete', 'manage'],
  expenses: ['create', 'read', 'update', 'delete', 'manage'],
  system: ['create', 'read', 'update', 'delete', 'manage'],
  devices: ['create', 'read', 'update', 'delete', 'manage'],
  audit: ['read'],
} as const;

// Actions implied by a resource-level `*.manage` permission.
const MANAGE_IMPLIED_ACTIONS = new Set(['create', 'update', 'delete']);

export function hasPermission(role: string, permission: string): boolean {
  const permissions = ROLE_PERMISSIONS[role];
  if (!permissions) return false;
  if (permissions.includes('*')) return true;
  if (permissions.includes(permission)) return true;

  // `<resource>.manage` implies create/update/delete on that resource.
  const separatorIndex = permission.lastIndexOf('.');
  if (separatorIndex > 0) {
    const resource = permission.slice(0, separatorIndex);
    const action = permission.slice(separatorIndex + 1);
    if (MANAGE_IMPLIED_ACTIONS.has(action) && permissions.includes(`${resource}.manage`)) {
      return true;
    }
  }

  return false;
}
